name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
      - name: Test with pytest
        # Below, we first run pytest in the `tests/` folder. Because we use a `src`
        # layout, this will fail if the package is not installed correctly.
        # Afterwards, we execute all doctests in the `src` tree. This will NOT run with
        # the installed code, but it doesn't matter, because we already know it is
        # installable from the first line.
        run: |
          COVERAGE_FILE=".coverage.tests" pytest --cov=lydata --cov-config=pyproject.toml tests
          COVERAGE_FILE=".coverage.docs" pytest --cov=lydata --cov-config=pyproject.toml --doctest-modules src
      - name: Add coverage comment
        if: success() || failure()
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_COVERAGE_FILES: true
